name: Create Release

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '#publish')"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Generate release tag
        uses: mosfetlang/dev-tagger-action@v1
        with:
          tag-prefix: 'v'
          origin: 'origin'
