name: Create Release

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Generate release tag
        uses: mosfetlang/dev-tagger-action@v1
        with:
          tag-prefix: 'my-tag-'
          origin: 'origin2'
